name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -sSf https://sh.rustup.rs | sh -s -- -y
      - run: export PATH="$HOME/.cargo/bin:$PATH" && make
      - uses: actions/upload-artifact@v4
        with:
          name: default.3gx
          path: default.3gx
